### ISSUE TITLE
there is an v1.0.45 in ansble galaxy

### ISSUE THREAD

**Issue by sakoula** [Oefenweb/ansible-ca-certificates#4]
[WARNING]: - Oefenweb.ca_certificates (v1.0.45) is already installed - use --force to change version to unspecified

**Comment by tersmitten** [comment]
What is the problem?

I'm not always "releasing" every tag I push, so there're definitely more tags than releases.

**Comment by sakoula** [comment]
ok sorry for this. I thought you forgot it. I was trying to be helpful. btw really great work with all your modules.

**Comment by tersmitten** [comment]
Thanks!
